name: Pixel Adventures
favicon: null
layout_spectrum: 0.5358122489415109
typography_spectrum: 0.5359635192435235
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.32062976877205074
  lightness: 0.8841463222634047
  saturation: 0.13266813708469272
  rhythmicContrast: 0.10146646946668625
purpose: []
